# Generated by Django 4.2.5 on 2023-11-07 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('entrada', models.IntegerField(choices=[(1, 'Llamada'), (2, 'Correo')], default=1)),
                ('estado', models.IntegerField(choices=[(1, 'En Espera'), (2, 'Cerrada'), (3, 'Pendiente Recordatorio'), (4, 'Pendiente Cerrar')], default=1)),
                ('nivel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, 'Proveedor')], default=1)),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2)),
                ('sistema', models.IntegerField(choices=[(1, 'CIDI'), (2, 'CESOL'), (3, 'VERTEX'), (4, 'CESIM'), (5, 'XETID'), (6, 'OTRA')], default=1)),
                ('grupo', models.IntegerField(choices=[(1, 'Especialistas de Desarrollo'), (2, 'Etecsa'), (3, 'Soporte Técnico')], default=1)),
                ('organizacion', models.IntegerField(choices=[(1, 'AGR'), (2, 'AIN'), (3, 'ANPP'), (4, 'BanMet'), (5, 'BCC'), (6, 'CAP-Camaguey'), (7, 'CAP-Granma'), (8, 'CAP-Guantánamo'), (9, 'CAP-La Habana'), (10, 'CAP-Las Tunas'), (11, 'CAP-Matanzas'), (12, 'CAP-Mayabeque'), (13, 'CAP-Pinar del Río'), (14, 'CCOIFP'), (15, 'CCPCC'), (16, 'CEDESA'), (17, 'CEJ'), (18, 'Centro Soporte')], default=1, verbose_name='Organización')),
                ('respuesta', models.TextField(blank=True, max_length=500, null=True, verbose_name='Respuesta')),
                ('fecha_creado', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
